name: Build Extension

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    # Build WASM from source.
    steps:
      - uses: actions/checkout@v4
      - uses: robinraju/release-downloader@v1.11
        with:
          repository: 'WebAssembly/wasi-sdk'
          tag: 'wasi-sdk-22'
          fileName: 'wasi-sysroot-22.0.tar.gz'
          extract: true
      - name: Setup WASI_SYSROOT
        run: |
              echo "WASI_SYSROOT=$(echo $GITHUB_WORKSPACE)/wasi-sysroot/" >> $GITHUB_ENV
              echo $WASI_SYSROOT
              ls -f $WASI_SYSROOT
      - name: Download latest clang
        run: |
              sudo apt update
              wget https://apt.llvm.org/llvm.sh
              chmod +x ./llvm.sh
              sudo ./llvm.sh 17
              clang --version
              clang-17 --version
      - name: Add target
        run: rustup target add wasm32-wasi
      - name: Build WASI
        run: cargo build --release --target wasm32-wasi --verbose
        env: # Somehow this VM has clang14 by default, which is not supported...
          CC: clang-17
          CXX: clang++-17
      - name: Build Desktop
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose