name: Deploy Extension

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create release folder
        run: mkdir -p ./bin/
      - name: Download desktop binary
        uses: actions/download-artifact@v4
        with:
          name: desktop
          path: ./bin
      - name: Download wasi binary
        uses: actions/download-artifact@v4
        with:
          name: wasi
          path: ./bin
      - name: Zip binary
        run: zip -v -r shader_language_server.zip ./bin
      - name: Create release
        run: gh release upload $GITHUB_REF shader_language_server.zip