name: Deploy Extension

on:
  release:
    types: [released]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Required for release upload
      - name: Create release folder
        run: mkdir -p ./bin/
      - name: Download desktop binary
        uses: actions/download-artifact@v4
        with:
          name: desktop
          path: ./bin
      - name: Download wasi binary
        uses: actions/download-artifact@v4
        if: ${{ vars.COMPILE_WASI == 'true' }}
        with:
          name: wasi
          path: ./bin
      - name: Zip binary
        run: zip -v -r -j shader-language-server.zip ./bin
      - name: Create release
        run: gh release upload ${{ github.ref_name }} shader-language-server.zip
        env:
          GH_TOKEN: ${{ github.token }}

  publish:
    runs-on: ubuntu-latest
    needs: deploy
    # Skip pre-release
    if: github.event_name == 'release' && github.event.action == 'released'

    steps:
      - uses: actions/checkout@v4 # Required for release upload
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}